### ISSUE TITLE
`__unused` conflicts with old glibc's bits/stat.h

### ISSUE THREAD

**Issue by netbsduser** [Zer0-One/libnv-portable#1]
Old versions of glibc used `__unused` inappropriate in `bits/stat.h`, and this causes problems to erupt when that header is included after `__unused` is `#define`'d away. They fixed this in bminor/glibc@d1d9eaf478b7d3a11a599c120498b79fe5629a61 but it persists in older systems which did not update.

`libbsd` however in recent versions also just `#define`s `__unused` away, so it presumably isn't too big of a problem to expect newer versions of glibc.

**Comment by Zer0-One** [comment]
I don't think this is one we'll worry about. I agree that it's probably reasonable to expect a version of glibc from within the last 7 years :P
